version: "3.9"

services:
  backend:
    build: backend
    image: taskwwwarrior/backend
    restart: always
    volumes:
      - ./backend/:/app
      - django-static:/static
    networks:
      - backnet

  frontend:
    build: frontend
    image: taskwwwarrior/frontend
    volumes:
      - ./frontend/:/app
      - frontend-build:/build
    networks:
      - backnet

  proxy:
    build: proxy
    image: taskwwwarrior/proxy
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontnet
      - backnet
    volumes:
      - frontend-build:/frontend
      - django-static:/static
      - ./proxy/sslcerts:/sslcerts

volumes:
  django-static:
  frontend-build:

networks:
  frontnet:
  backnet: